from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 800, 600))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuImage_Processing = QtWidgets.QMenu(self.menubar)
        self.menuImage_Processing.setObjectName("menuImage_Processing")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Image = QtWidgets.QAction(MainWindow)
        self.actionOpen_Image.setObjectName("actionOpen_Image")
        self.actionROI = QtWidgets.QAction(MainWindow)
        self.actionROI.setObjectName("actionROI")
        self.actionImage_histogram = QtWidgets.QAction(MainWindow)
        self.actionImage_histogram.setObjectName("actionImage_histogram")
        self.actionColor_space = QtWidgets.QAction(MainWindow)
        self.actionColor_space.setObjectName("actionColor_space")
        self.actionColor_spaceMenu = QtWidgets.QAction(MainWindow)
        self.actionColor_spaceMenu.setObjectName("actionColor_spaceMenu")
        self.actionThresholding = QtWidgets.QAction(MainWindow)
        self.actionThresholding.setObjectName("actionThresholding")
        self.actionHistogram_Equalization = QtWidgets.QAction(MainWindow)
        self.actionHistogram_Equalization.setObjectName("actionHistogram_Equalization")
        self.menuFile.addAction(self.actionOpen_Image)
        self.menuSetting.addAction(self.actionROI)
        self.menuSetting.addAction(self.actionImage_histogram)
        self.menuSetting.addAction(self.actionColor_space)
        self.menuImage_Processing.addAction(self.actionColor_spaceMenu)
        self.menuImage_Processing.addAction(self.actionThresholding)
        self.menuImage_Processing.addAction(self.actionHistogram_Equalization)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuImage_Processing.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.menuImage_Processing.setTitle(_translate("MainWindow", "Image Processing"))
        self.actionOpen_Image.setText(_translate("MainWindow", "Open_Image"))
        self.actionROI.setText(_translate("MainWindow", "ROI"))
        self.actionImage_histogram.setText(_translate("MainWindow", "Image histogram"))
        self.actionColor_space.setText(_translate("MainWindow", "Color space"))
        self.actionColor_spaceMenu.setText(_translate("MainWindow", "Color spaceMenu"))
        self.actionThresholding.setText(_translate("MainWindow", "Thresholding"))
        self.actionHistogram_Equalization.setText(_translate("MainWindow", "Histogram Equalization"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())