# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import cv2 as cv
from PyQt5.QtGui import QImage, QPixmap
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.picturelabel = QtWidgets.QLabel(self.centralwidget)
        self.picturelabel.setGeometry(QtCore.QRect(10, 10, 751, 571))
        self.picturelabel.setObjectName("NO Picture")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(780, 30, 51, 31))
        self.label_2.setObjectName("label_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(830, 30, 231, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuImage_Processing = QtWidgets.QMenu(self.menubar)
        self.menuImage_Processing.setObjectName("menuImage_Processing")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.ActionOpen = QtWidgets.QAction(MainWindow)
        self.ActionOpen.setObjectName("ActionOpen")
        self.ActionROI = QtWidgets.QAction(MainWindow)
        self.ActionROI.setObjectName("ActionROI")
        self.ActionImage_histogram = QtWidgets.QAction(MainWindow)
        self.ActionImage_histogram.setObjectName("ActionImage_histogram")
        self.ActionColor_space = QtWidgets.QAction(MainWindow)
        self.ActionColor_space.setObjectName("ActionColor_space")
        self.actionColor_spaceMenu = QtWidgets.QAction(MainWindow)
        self.actionColor_spaceMenu.setObjectName("actionColor_spaceMenu")
        self.actionThresholding = QtWidgets.QAction(MainWindow)
        self.actionThresholding.setObjectName("actionThresholding")
        self.actionHistogram_Equalization = QtWidgets.QAction(MainWindow)
        self.actionHistogram_Equalization.setObjectName("actionHistogram_Equalization")
        self.menuFile.addAction(self.ActionOpen)
        self.menuSetting.addAction(self.ActionROI)
        self.menuSetting.addAction(self.ActionImage_histogram)
        self.menuSetting.addAction(self.ActionColor_space)
        self.menuImage_Processing.addAction(self.actionColor_spaceMenu)
        self.menuImage_Processing.addAction(self.actionThresholding)
        self.menuImage_Processing.addAction(self.actionHistogram_Equalization)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuImage_Processing.menuAction())
        self._connectActions()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.picturelabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.menuImage_Processing.setTitle(_translate("MainWindow", "Image Processing"))
        self.ActionOpen.setText(_translate("MainWindow", "Open_Image"))
        self.ActionROI.setText(_translate("MainWindow", "ROI"))
        self.ActionImage_histogram.setText(_translate("MainWindow", "Image histogram"))
        self.ActionColor_space.setText(_translate("MainWindow", "Color space"))
        self.actionColor_spaceMenu.setText(_translate("MainWindow", "Color spaceMenu"))
        self.actionThresholding.setText(_translate("MainWindow", "Thresholding"))
        self.actionHistogram_Equalization.setText(_translate("MainWindow", "Histogram Equalization"))

    def _connectActions(self):#按鍵觸發
        self.ActionOpen.triggered.connect(self.openSlot)

    def openSlot(self):
        filename, _ = QFileDialog.getOpenFileName(self, 'Open Image', 'Image', '*.png *.jpg *.bmp')
        if filename is '':
            return
        self.img = cv.imread(filename, -1)
        if self.img.size == 1:
            return
        self.showImage()

    def showImage(self):
        height, width, Channel = self.img.shape
        bytesPerline = 3 * width
        self.qImg = QImage(self.img.data, width, height, bytesPerline, QImage.Format_RGB888).rgbSwapped()
        self.picturelabel.setPixmap(QPixmap.fromImage(self.qImg))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
